### ISSUE TITLE
Submit chemicals to ChEBI

### ISSUE THREAD

**Issue by cthoyt** [hemekg/terminology#9]
There are four chemicals listed in this terminology:

- [ ] HM00010, chemical role, cytolysin, pmid:29956069 - Some pathogens are capable of causing hemolysis by cytolytic toxins
- [ ] HM00023, chemical, Labile iron, pmid:30281034 - Transferrin (Tf) saturation and, finally, accumulation of labile plasma iron (LPI)
- [ ] HM00026, chemical role, oxidative reactions, pmid:30281034 - Hpx-hemin complex prevents oxidative reactions
- [ ] HM00050, chemical role, nitrite oxidation, pmid:26202471 - Faster rates for nitrite oxidation in the lag phase were positively associated with higher concentrations of extracellular free heme at d7 and d35.

1. Cytolysin is actually an interesting chemical role. The curation in HemeKG leaves much to be desired, since it basically only contains a single correlation statement whose curation needs to be revisited/redone
2. Lability is a state of the entity and not the entity itself, so I'm not sure what to do about this one.
3. From the description, this term is not even a chemical/role
4.  From the description, this term is also not even a chemical/role

**Comment by cthoyt** [comment]
@Fahumayun please find small molecule examples of cytolysins. I started reading https://en.wikipedia.org/wiki/Cytolysin, but I only found examples that were macromolecules (e.g., proteins from bacteria)

**Comment by Fahumayun** [comment]
1. Labile iron, I wasn't sure so I added "?"  to the class name.
2. Oxidation reactions, I am not sure whether to add "biological process" or "?".
3. Nitrite oxidation is defined as an essential step in transformations of fixed nitrogen and surely it can't be a biological process.
